[2025-01-13T14:05:44.255+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: finflow_source_data_pipeline.load_to_gcs_bq.load_date_to_bq manual__2025-01-13T14:04:46.457822+00:00 [queued]>
[2025-01-13T14:05:44.334+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: finflow_source_data_pipeline.load_to_gcs_bq.load_date_to_bq manual__2025-01-13T14:04:46.457822+00:00 [queued]>
[2025-01-13T14:05:44.340+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2025-01-13T14:05:44.423+0000] {taskinstance.py:1382} INFO - Executing <Task(GCSToBigQueryOperator): load_to_gcs_bq.load_date_to_bq> on 2025-01-13 14:04:46.457822+00:00
[2025-01-13T14:05:44.486+0000] {standard_task_runner.py:57} INFO - Started process 1611 to run task
[2025-01-13T14:05:44.508+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'finflow_source_data_pipeline', 'load_to_gcs_bq.load_date_to_bq', 'manual__2025-01-13T14:04:46.457822+00:00', '--job-id', '178', '--raw', '--subdir', 'DAGS_FOLDER/finflow.py', '--cfg-path', '/tmp/tmpbfxd2g9s']
[2025-01-13T14:05:44.534+0000] {standard_task_runner.py:85} INFO - Job 178: Subtask load_to_gcs_bq.load_date_to_bq
[2025-01-13T14:05:44.863+0000] {task_command.py:416} INFO - Running <TaskInstance: finflow_source_data_pipeline.load_to_gcs_bq.load_date_to_bq manual__2025-01-13T14:04:46.457822+00:00 [running]> on host ab4e86dc450e
[2025-01-13T14:05:45.317+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='finflow_source_data_pipeline' AIRFLOW_CTX_TASK_ID='load_to_gcs_bq.load_date_to_bq' AIRFLOW_CTX_EXECUTION_DATE='2025-01-13T14:04:46.457822+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-13T14:04:46.457822+00:00'
[2025-01-13T14:05:45.321+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2025-01-13T14:05:45.331+0000] {connection.py:232} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2025-01-13T14:05:45.339+0000] {base.py:73} INFO - Using connection ID 'google_cloud_default' for task execution.
[2025-01-13T14:05:45.352+0000] {gcs_to_bigquery.py:376} INFO - Using existing BigQuery table for storing data...
[2025-01-13T14:05:45.844+0000] {gcs_to_bigquery.py:380} INFO - Executing: {'load': {'autodetect': True, 'createDisposition': 'CREATE_IF_NEEDED', 'destinationTable': {'projectId': 'finflow-analytics-production', 'datasetId': 'finflow_raw', 'tableId': 'src_dates'}, 'sourceFormat': 'PARQUET', 'sourceUris': ['gs://finflow-analytics-data/raw/dates/2025-01-13/dates.parquet'], 'writeDisposition': 'WRITE_APPEND', 'ignoreUnknownValues': False}}
[2025-01-13T14:05:45.855+0000] {bigquery.py:1595} INFO - Inserting job ***_finflow_source_data_pipeline_load_to_gcs_bq_load_date_to_bq_2025_01_13T14_04_46_457822_00_00_49e723a0889ee1ce080ae4d429f2481b
[2025-01-13T14:05:47.225+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/google/cloud/transfers/gcs_to_bigquery.py", line 439, in execute
    job.result(timeout=self.result_timeout, retry=self.result_retry)
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/bigquery/job/base.py", line 922, in result
    return super(_AsyncJob, self).result(timeout=timeout, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/google/api_core/future/polling.py", line 261, in result
    raise self._exception
google.api_core.exceptions.BadRequest: 400 Provided Schema does not match Table finflow-analytics-production:finflow_raw.src_dates. Field date_key has changed mode from REQUIRED to NULLABLE
[2025-01-13T14:05:47.269+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=finflow_source_data_pipeline, task_id=load_to_gcs_bq.load_date_to_bq, execution_date=20250113T140446, start_date=20250113T140544, end_date=20250113T140547
[2025-01-13T14:05:47.316+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 178 for task load_to_gcs_bq.load_date_to_bq (400 Provided Schema does not match Table finflow-analytics-production:finflow_raw.src_dates. Field date_key has changed mode from REQUIRED to NULLABLE; 1611)
[2025-01-13T14:05:47.358+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-01-13T14:05:47.509+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
